# Generated by Django 6.0.2 on 2026-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
