# Generated by Django 6.0.2 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_trip_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
    ]
